#!/bin/sh

CFG_PATH="/etc/asterisk/"
GUI_CFG_PREFIX="gui_"
CFG_FILES="http.conf manager.conf users.conf"

for i in $CFG_FILES; do
	if [ -f $CFG_PATH$i ]; then
		mv $CFG_PATH$i $CFG_PATH$i".backup"
	fi
	cp $CFG_PATH$GUI_CFG_PREFIX$i $CFG_PATH$i
done
